[build.environment]
HUGO_VERSION = "0.81.0"
NODE_VERSION = "15.5.1"
NPM_VERSION = "7.3.0"

[build]
base = "/"
publish = "/site/dist"
functions = "functions/"
command = "npm run netlify-build"

[context.production]
command = "npm run netlify-build"

[context.deploy-preview]
command = "npm run build:preview"


[[plugins]]
package = "netlify-plugin-a11y"
[plugins.inputs]
checkPaths = ['/']
resultMode = "warn"

[[plugins]]
package = "/plugins/netlify-sanity-md"
[plugins.inputs]
#checkPaths = ['/']
#resultMode = 'warn'

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = 'max-age=31536000; includeSubDomains; preload'
Content-Security-Policy = "default-src data: 'unsafe-inline' 'unsafe-eval' https:; script-src data: 'unsafe-inline' 'unsafe-eval' https: blob:; style-src data: 'unsafe-inline' https:; img-src data: https: blob:; font-src data: https:; connect-src https: wss: blob:; media-src https: blob:; object-src https:; child-src https: data: blob:; form-action https:; block-all-mixed-content"
Feature-Policy = "geolocation 'self'; microphone 'none'; camera 'none'"
Referrer-Policy = "no-referrer"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "max-age=604800, public"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "max-age=604800, public"
