[build.environment]
NPM_VERSION = "6.4.1"
YARN_VERSION = "1.12.1"

[build]
command = "yarn build"
publish = "dist"

[context.deploy-preview]
command = "yarn build:preview"

[[plugins]]
package = "netlify-plugin-a11y"

[[plugins]]
package = "/plugins/netlify-sanity-md"

[plugins.inputs]
checkPaths = ['/']

resultMode = "warn"
