[build.environment]
NPM_VERSION = "6.4.1"
YARN_VERSION = "1.12.1"

[build]
command = "yarn build"
publish = "dist"

[context.deploy-preview]
command = "yarn build:preview"

[[plugins]]
package = "/plugins/netlify-sanity-md"

[[plugins]]
package = "netlify-plugin-a11y"

[plugins.inputs]
checkPaths = ['/']

resultMode = "warn"

[[headers]]
for = "/*"
[headers.values]
Refferer-Policy = "no-referrer"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
